import type { App, Installation, Task, Webhook, Lead } from "./types"

export const mockApps: App[] = [
  {
    id: "1",
    name: "Lead Capture Pro",
    description: "Advanced lead capture and management system with automated follow-ups",
    version: "2.1.0",
    category: "Marketing",
    icon: "/lead-capture-app-icon.png",
    status: "active",
    installation_count: 45,
    rating: 4.8,
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
    features: ["Lead Forms", "Email Integration", "Analytics Dashboard", "CRM Sync"],
    screenshots: ["/lead-capture-dashboard.png", "/lead-forms-interface.png"],
    developer: "BlackHold Marketing Team",
    price: 99,
    tags: ["marketing", "leads", "automation"],
  },
  {
    id: "2",
    name: "Task Scheduler",
    description: "Automated task scheduling and execution system for workflow optimization",
    version: "1.5.2",
    category: "Productivity",
    icon: "/task-scheduler-app-icon.png",
    status: "active",
    installation_count: 32,
    rating: 4.6,
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-03-15T00:00:00Z",
    features: ["Cron Jobs", "Task Monitoring", "Error Handling", "Notifications"],
    screenshots: ["/task-scheduler-dashboard.png", "/task-monitoring-interface.png"],
    developer: "BlackHold DevOps Team",
    price: 149,
    tags: ["automation", "scheduling", "productivity"],
  },
  {
    id: "3",
    name: "Webhook Manager",
    description: "Centralized webhook management and monitoring system",
    version: "1.2.1",
    category: "Integration",
    icon: "/webhook-manager-app-icon.png",
    status: "active",
    installation_count: 28,
    rating: 4.4,
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-02-28T00:00:00Z",
    features: ["Webhook Endpoints", "Event Monitoring", "Retry Logic", "Security"],
    screenshots: ["/webhook-manager-dashboard.png"],
    developer: "BlackHold Integration Team",
    price: 79,
    tags: ["webhooks", "integration", "monitoring"],
  },
]

export const mockInstallations: Installation[] = [
  {
    id: "1",
    app_id: "1",
    user_id: "1",
    status: "installed",
    installed_at: "2024-03-01T00:00:00Z",
    config: { notifications: true, auto_sync: true },
  },
  {
    id: "2",
    app_id: "2",
    user_id: "1",
    status: "installed",
    installed_at: "2024-03-05T00:00:00Z",
    config: { schedule_interval: "1h", max_retries: 3 },
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    app_id: "2",
    name: "Daily Lead Sync",
    description: "Synchronize leads from external sources",
    status: "completed",
    scheduled_at: "2024-03-20T09:00:00Z",
    completed_at: "2024-03-20T09:05:00Z",
    result: { processed: 15, errors: 0 },
  },
  {
    id: "2",
    app_id: "2",
    name: "Weekly Report Generation",
    description: "Generate weekly performance reports",
    status: "pending",
    scheduled_at: "2024-03-25T10:00:00Z",
  },
  {
    id: "3",
    app_id: "1",
    name: "Email Campaign Sync",
    description: "Sync email campaign data with CRM",
    status: "pending",
    scheduled_at: "2024-03-21T14:00:00Z",
  },
  {
    id: "4",
    app_id: "3",
    name: "Webhook Health Check",
    description: "Verify all webhook endpoints are responding",
    status: "completed",
    scheduled_at: "2024-03-19T08:00:00Z",
    completed_at: "2024-03-19T08:02:00Z",
    result: { processed: 12, errors: 0 },
  },
]

export const mockWebhooks: Webhook[] = [
  {
    id: "1",
    app_id: "1",
    url: "https://api.blackhold.com/webhooks/leads",
    events: ["lead.created", "lead.updated"],
    status: "active",
    secret: "wh_secret_123456789abcdef",
    created_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "2",
    app_id: "2",
    url: "https://api.blackhold.com/webhooks/tasks",
    events: ["task.started", "task.completed", "task.failed"],
    status: "active",
    secret: "wh_secret_987654321fedcba",
    created_at: "2024-03-05T00:00:00Z",
  },
  {
    id: "3",
    app_id: "3",
    url: "https://external-service.com/webhooks/blackhold",
    events: ["app.installed", "app.uninstalled"],
    status: "inactive",
    secret: "wh_secret_abcdef123456789",
    created_at: "2024-02-28T00:00:00Z",
  },
]

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john@example.com",
    company: "Tech Corp",
    phone: "+1-555-0123",
    source: "Website Form",
    status: "new",
    created_at: "2024-03-20T14:30:00Z",
    notes: "Interested in enterprise solution",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah@startup.com",
    company: "Startup Inc",
    source: "LinkedIn",
    status: "contacted",
    created_at: "2024-03-19T11:15:00Z",
    notes: "Follow up next week",
  },
]
